services:
  - type: web
    name: peachmini-api
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8787
      - key: PB_URL
        sync: false
      - key: OPENAI_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: WEBAPP_ORIGIN
        sync: false
