# --- render.yaml ---
services:
  - type: web
    name: peachmini-pb
    env: docker
    plan: free
    region: frankfurt
    autoscaling: false
    healthCheckPath: /
    # NOTE: Persistent disk требует платный план ($7/мес)
    # Без диска данные будут теряться при каждом редеплое
    # disk:
    #   name: pbdata
    #   mountPath: /pb/pb_data
    #   sizeGB: 1
# -------------------

