name: Heartbeat

on:
  schedule:
    - cron: "*/5 * * * *"  # Каждые 5 минут
  workflow_dispatch:  # Возможность запуска вручную

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Health
        id: api
        run: |
          curl -fsSL https://peach-mini-qt4sgywv0-trsoyoleg-4006s-projects.vercel.app/api/health || exit 1
        continue-on-error: true

      - name: Check Frontend Health
        id: front
        run: |
          curl -fsSL https://peach-e0dyhhciv-trsoyoleg-4006s-projects.vercel.app/health || exit 1
        continue-on-error: true

      - name: Notify Telegram on API Failure
        if: steps.api.outcome == 'failure'
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.ADMIN_TG_ID }} \
            -d text="🚨 Heartbeat FAIL: API /health не отвечает"

      - name: Notify Telegram on Frontend Failure
        if: steps.front.outcome == 'failure'
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.ADMIN_TG_ID }} \
            -d text="🚨 Heartbeat FAIL: Frontend /health не отвечает"

      - name: Fail job if any check failed
        if: steps.api.outcome == 'failure' || steps.front.outcome == 'failure'
        run: exit 1

      - name: Success notification
        if: steps.api.outcome == 'success' && steps.front.outcome == 'success'
        run: echo "✅ All systems operational"
